
package com.sia.base.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "BaseServices", targetNamespace = "", wsdlLocation = "file:/C:/jprojects/WebServices/work/base/BaseServices.wsdl")
public class BaseServices
    extends Service
{

    private final static URL BASESERVICES_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.sia.base.ws.BaseServices.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.sia.base.ws.BaseServices.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/jprojects/WebServices/work/base/BaseServices.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/jprojects/WebServices/work/base/BaseServices.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        BASESERVICES_WSDL_LOCATION = url;
    }

    public BaseServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaseServices() {
        super(BASESERVICES_WSDL_LOCATION, new QName("", "BaseServices"));
    }

    /**
     * 
     * @return
     *     returns BaseServicesPortType
     */
    @WebEndpoint(name = "BaseServicesPort")
    public BaseServicesPortType getBaseServicesPort() {
        return super.getPort(new QName("", "BaseServicesPort"), BaseServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaseServicesPortType
     */
    @WebEndpoint(name = "BaseServicesPort")
    public BaseServicesPortType getBaseServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("", "BaseServicesPort"), BaseServicesPortType.class, features);
    }

}
